exports.menuList = [
  {
    time: "Breakfast",
    day: "Monday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Tuesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Wednesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Thursday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Friday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Saturday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Sunday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Monday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Tuesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Wednesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Thursday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Friday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Saturday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Breakfast",
    day: "Sunday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Monday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Tuesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Wednesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Thursday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Friday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Saturday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Sunday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Monday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Tuesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Wednesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Thursday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Friday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Saturday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Lunch",
    day: "Sunday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Monday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Tuesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Wednesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Thursday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Friday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Saturday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Sunday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Monday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Tuesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Wednesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Thursday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Friday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Saturday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Tea",
    day: "Sunday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Monday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Tuesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Wednesday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Thursday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Friday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Saturday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Sunday",
    mess_type: "North",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Monday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Tuesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Wednesday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Thursday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Friday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Saturday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
  {
    time: "Dinner",
    day: "Sunday",
    mess_type: "South",
    description: "Chappathi,Kurma,Cooffe,Tea",
  },
];
